### PR TITLE
Week 1 HW

### PR DESCRIPTION
**Pull request by jrsarrat**

### CODE REVIEW

**Comment by julie-scherer** [comment]
hey @jrsarrat, i updated your branch. now you need to push a dummy commit / change to the submission/ folder to rerun the workflow

**Comment by julie-scherer** [comment]
Hi, this is human Julie 😄 Just a heads up - I synced and rebased your remote branch, so please be sure to run this command before attempting to push any local changes to the remote branch or it might give you a conflict error :(

```
git pull origin <your_branch> --rebase
```

**Comment by jrsarrat** [comment]
[like]  Jilliane Sarratt reacted to your message:
________________________________

**Comment by jrsarrat** [comment]
Good morning, human Julie (lol)!

Thank you! Clearly, the information you have in GitHub on how to submit the homework isn’t clear enough for me 🥴 Would you mind providing me instructions for dummies, please? I want to make sure I am proficient in this part of data engineering.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request closed without merging**
